name: Gradle Package

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      distribution:
        description: 'Distribution name'
        required: true
        default: 'unspecified'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Publish to GitHub Packages
      run: ./gradlew publish -Pdistribution=${{ github.event.inputs.distribution }}
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
