# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Publish

on:

  push:

    branches:

      - main  # 或者你想要触发工作流程的分支

  pull_request:

    branches:

      - main  # 或者你想要触发工作流程的分支

  workflow_dispatch:  # 手动触发工作流程

jobs:

  build-and-publish:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code

        uses: actions/checkout@v2

      - name: Set up JDK

        uses: actions/setup-java@v2

        with:

          java-version: '17'  # 或者你想要使用的 Java 版本

      - name: Build and publish

        run: |

          ./gradlew clean build publishToMavenLocal

      - name: Manual approval

        if: github.event_name == 'workflow_dispatch'

        uses: stefanzweifel/git-auto-approve-action@v2.3.0

        with:

          repo-token: ${{ secrets.GITHUB_TOKEN }}


    
